## Test photErrorModel Randomization

In [1]:
import sys
import numpy as np

# add the PhotoZDC1/src to your path
package_dir = '/home/erfan/erfan-proj/packages'
sys.path.insert(0, f'{package_dir}/PhotoZDC1/src') # LSST error model

import photErrorModel as pem

##### Magnitudes to work with

In [2]:
# ugrizy magnitudes for three galaxies (intentionally identical) - not realistic, just for testing
mag_true = np.array([[17, 18, 19, 20, 21, 22],
                     [17, 18, 19, 20, 21, 22],
                     [17, 18, 19, 20, 21, 22]]).T

##### Create an instance of the class (#1)

In [3]:
# set up LSST error model from PhotozDC1 codebase
errmodel_1st = pem.LSSTErrorModel(pars={'randSeed': 2019})

# if you forgot to put {'nYrObs': 2.5} etc. in pars you can always do it after
errmodel_1st.nYrObs = 2.5

# if you forgot to put {'randSeed': 2019} in pars you are NOT allowed to do it late
# errmodel_1st.randSeed = 2019 # WRONG!

# let's vectorize the function so that we can pass e.g. a 2D array to it
getObs_1st = np.vectorize(errmodel_1st.getObs)

Obs_1st = np.array([getObs_1st(mag_true[b],f'LSST_{band}') for b, band in enumerate('ugrizy')]).T

Obs_1st

array([[[1.70039580e+01, 1.80038608e+01, 1.90064258e+01, 1.99963946e+01,
         2.09971007e+01, 2.19521742e+01],
        [2.57707474e-03, 2.53310328e-03, 2.52813575e-03, 2.71001615e-03,
         4.51719429e-03, 2.79037299e-02]],

       [[1.69985884e+01, 1.79941534e+01, 1.89999511e+01, 1.99980898e+01,
         2.10024488e+01, 2.20129794e+01],
        [2.57669158e-03, 2.53280189e-03, 2.52794115e-03, 2.71048738e-03,
         4.53267926e-03, 2.94984759e-02]],

       [[1.70005742e+01, 1.80004106e+01, 1.90034207e+01, 2.00020827e+01,
         2.10036188e+01, 2.20357889e+01],
        [2.57683306e-03, 2.53299584e-03, 2.52804525e-03, 2.71160183e-03,
         4.53608023e-03, 3.01202922e-02]]])

In [4]:
if np.alltrue((Obs_1st[0] != Obs_1st[1]) & (Obs_1st[0] != Obs_1st[2])):
    print('Success! Galaxies have different observed magnitudes and errors.')
else:
    print('Something went wrong!')

Success! Galaxies have different observed magnitudes and errors.


##### Create a new instance of the class with the same random seed as the first one (#2)

In [5]:
# FRESH setup
errmodel_2nd = pem.LSSTErrorModel(pars={'randSeed': 2019})
errmodel_2nd.nYrObs = 2.5
getObs_2nd = np.vectorize(errmodel_2nd.getObs)
Obs_2nd = np.array([getObs_2nd(mag_true[b],f'LSST_{band}') for b, band in enumerate('ugrizy')]).T
Obs_2nd

array([[[1.70039580e+01, 1.80038608e+01, 1.90064258e+01, 1.99963946e+01,
         2.09971007e+01, 2.19521742e+01],
        [2.57707474e-03, 2.53310328e-03, 2.52813575e-03, 2.71001615e-03,
         4.51719429e-03, 2.79037299e-02]],

       [[1.69985884e+01, 1.79941534e+01, 1.89999511e+01, 1.99980898e+01,
         2.10024488e+01, 2.20129794e+01],
        [2.57669158e-03, 2.53280189e-03, 2.52794115e-03, 2.71048738e-03,
         4.53267926e-03, 2.94984759e-02]],

       [[1.70005742e+01, 1.80004106e+01, 1.90034207e+01, 2.00020827e+01,
         2.10036188e+01, 2.20357889e+01],
        [2.57683306e-03, 2.53299584e-03, 2.52804525e-03, 2.71160183e-03,
         4.53608023e-03, 3.01202922e-02]]])

In [6]:
if np.alltrue(Obs_1st == Obs_2nd):
    print('Success! Obs_1st and Obs_2nd are exactly the same.')
else:
    print('Something went wrong!')        

Success! Obs_1st and Obs_2nd are exactly the same.


##### Create a new instance of the class with a different random seed than the first two (#3)

In [7]:
# another FRESH setup
errmodel_3rd = pem.LSSTErrorModel(pars={'randSeed': 1905})
errmodel_3rd.nYrObs = 2.5
getObs_3rd = np.vectorize(errmodel_3rd.getObs)
Obs_3rd = np.array([getObs_3rd(mag_true[b],f'LSST_{band}') for b, band in enumerate('ugrizy')]).T
Obs_3rd

array([[[1.69976302e+01, 1.79981941e+01, 1.89973364e+01, 1.99993214e+01,
         2.10001691e+01, 2.19872099e+01],
        [2.57662341e-03, 2.53292700e-03, 2.52786299e-03, 2.71083044e-03,
         4.52606643e-03, 2.88116126e-02]],

       [[1.69953163e+01, 1.80002798e+01, 1.89992170e+01, 2.00068857e+01,
         2.10006190e+01, 2.20227294e+01],
        [2.57645903e-03, 2.53299177e-03, 2.52791918e-03, 2.71295084e-03,
         4.52737002e-03, 2.97626642e-02]],

       [[1.69999410e+01, 1.80046183e+01, 1.89979434e+01, 1.99951025e+01,
         2.09964392e+01, 2.20177337e+01],
        [2.57678792e-03, 2.53312692e-03, 2.52788111e-03, 2.70965774e-03,
         4.51528559e-03, 2.96270017e-02]]])

In [8]:
if np.alltrue(Obs_1st != Obs_3rd):
    print('Success! With a different random seed, galaxies would have different observed magnitudes and errors.')
else:
    print('Something went wrong!')

Success! With a different random seed, galaxies would have different observed magnitudes and errors.


##### Use the same instance of the class to get results for the same magnitudes again (#4)

In [9]:
Obs_4th = np.array([getObs_3rd(mag_true[b],f'LSST_{band}') for b, band in enumerate('ugrizy')]).T
Obs_4th

array([[[1.70001826e+01, 1.80007229e+01, 1.89985348e+01, 1.99954982e+01,
         2.10051493e+01, 2.19558314e+01],
        [2.57680514e-03, 2.53300555e-03, 2.52789878e-03, 2.70976745e-03,
         4.54053637e-03, 2.79971270e-02]],

       [[1.69967480e+01, 1.79998558e+01, 1.89983853e+01, 1.99985849e+01,
         2.10065673e+01, 2.20914498e+01],
        [2.57656070e-03, 2.53297860e-03, 2.52789431e-03, 2.71062524e-03,
         4.54467230e-03, 3.16940476e-02]],

       [[1.69928303e+01, 1.80000515e+01, 1.90013409e+01, 2.00058183e+01,
         2.09972090e+01, 2.20187007e+01],
        [2.57628282e-03, 2.53298468e-03, 2.52798279e-03, 2.71265025e-03,
         4.51750663e-03, 2.96532120e-02]]])

In [10]:
if np.alltrue(Obs_3rd != Obs_4th):
    print('Success! Same galaxies would have different observed magnitudes and errors if the created instance is reused.')
else:
    print('Something went wrong!')

Success! Same galaxies would have different observed magnitudes and errors if the created instance is reused.
